name: CodeCrux Web Technologies pvt ltd
description: CodeCrux designs and engineers production-grade AI systems, agents and intelligent workflows for the AI-native enterprise.
baseurl:
url: https://codecrux.com
redirect_to: https://codecrux.com

twitter_username: codecrux
github_username:  codecrux

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed

collections:
  cookies:
    output: true
